export type Meditation = {
  id: number;
  title: string;
  description: string;
  duration: number;
  img: string;
  category: Category;
  type: Type;
  reward: number;
  url: string;
  belongsTo: string;
};

export enum Category {
  all,
  focus,
  growth,
  confidence,
  sleep,
  anxiety,
  courses,
  beginners,
  unguided,
}

export enum Type {
  single,
  course,
}

export let meditations: Array<Meditation> = [
  {
    title: "Chronic Pain, Safe Place",
    description:
      "Learn to deal with chronic stress and ease the emotional stress it brings through breath work.",
    belongsTo: "none",
    category: Category.anxiety,
    img: "house.svg",
    type: Type.single,
    id: 36,
    duration: 828,
    reward: 15,
    url: "https://mcdn.podbean.com/mf/web/3x43dz/228_Relieve_Stress_and_Activate_Intuition_VOCALSaj10d.mp3",
  },
  {
    title: "A Sense of Gratitude",
    description:
      "In this meditation learn how to cultivate a sense of gratitude.",
    belongsTo: "none",
    category: Category.growth,
    img: "wateringPot.svg",
    type: Type.single,
    id: 37,
    duration: 1147,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/gjbfjp/365_Sense_of_Gratitude_VOCALS6inm8.mp3",
  },
  {
    title: "Relieve Stress, Activate Intuition",
    description:
      "Learn the secret to relieving stress, and activating your inner intuition",
    belongsTo: "none",
    category: Category.anxiety,
    img: "brain.svg",
    type: Type.single,
    id: 38,
    duration: 1225,
    reward: 21,
    url: "https://mcdn.podbean.com/mf/web/3x43dz/228_Relieve_Stress_and_Activate_Intuition_VOCALSaj10d.mp3",
  },
  {
    title: "Deep Sleep",
    description:
      "A 20 minute meditation for people looking to quickly fall into a deep sleep",
    belongsTo: "none",
    category: Category.sleep,
    img: "moon.svg",
    type: Type.single,
    id: 39,
    duration: 1285,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/4vxfi9/366_Deep_Sleep_VOCALS86ffx.mp3",
  },
  {
    title: "Meditation for Happiness",
    description:
      "Learn that happiness, just like anything else in life can be learned.",
    belongsTo: "none",
    category: Category.growth,
    img: "redTulips/tulip3.svg",
    type: Type.single,
    id: 40,
    duration: 1227,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/hu3net/372_Meditation_for_Happiness_VOCALS827d7.mp3",
  },
  {
    title: "Build Confidence",
    description:
      "Learn to feel confidence and break away from your negative thought patterns",
    belongsTo: "none",
    category: Category.confidence,
    img: "sunglasses.svg",
    type: Type.single,
    id: 41,
    duration: 1160,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/2aysdh/358_Experience_Confidence_VOCALS64r7q.mp3",
  },
  {
    title: "Emotional Balance",
    description:
      "Learn to balance your tricky emotions and experience peace & clarity",
    belongsTo: "none",
    category: Category.growth,
    img: "watermelon.svg",
    type: Type.single,
    id: 42,
    duration: 1143,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/etnx62/361_Emotional_Balance_VOCALSaba3g.mp3",
  },
  {
    title: "Confidence Meditation",
    description:
      "A guided meditation to build confidence and break away from your negative thought patterns",
    belongsTo: "none",
    category: Category.confidence,
    img: "candle.svg",
    type: Type.single,
    id: 43,
    duration: 845,
    reward: 15,
    url: "https://mcdn.podbean.com/mf/web/2aysdh/358_Experience_Confidence_VOCALS64r7q.mp3",
  },
  {
    title: "It Lies Within You",
    description:
      "Learn that confidence lies within you and how to bring it out",
    belongsTo: "none",
    category: Category.confidence,
    img: "gnome.svg",
    type: Type.single,
    id: 44,
    duration: 1154,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/2aysdh/358_Experience_Confidence_VOCALS64r7q.mp3",
  },
  {
    title: "How to Meditate",
    description: "Learn how to meditate and how simply it truly is",
    belongsTo: "none",
    category: Category.beginners,
    img: "books.svg",
    type: Type.single,
    id: 45,
    duration: 305,
    reward: 5,
    url: "https://mcdn.podbean.com/mf/web/tr4dnq/1403_How_To_Meditate_VOCALSbrsfv.mp3",
  },
  {
    title: "Relieve Anxiety",
    description:
      "In this guided meditation gain control over your anxiety & experience peace and calmness.",
    belongsTo: "none",
    category: Category.anxiety,
    img: "cloud.svg",
    type: Type.single,
    id: 46,
    duration: 609,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/y39bbt/1432_Guided_Meditation_for_Anxiety_10_min_VOCALSajbr7.mp3",
  },
  {
    title: "Good Morning, Positive Energy",
    description:
      "Learn how to cultive creatity and boost inspiration by being present.",
    belongsTo: "none",
    category: Category.growth,
    img: "eggs.svg",
    type: Type.single,
    id: 49,
    duration: 607,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/bgbwzn/1446C_Enhance_Creativity_and_Boost_Inspiration_10_min_VOCALSaiunb.mp3",
  },
  {
    title: "Affirmations",
    description: "Affirmations for health, wealth, love and happiness.",
    belongsTo: "none",
    category: Category.growth,
    img: "bee.svg",
    type: Type.single,
    id: 50,
    duration: 632,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/y39bbt/1432_Guided_Meditation_for_Anxiety_10_min_VOCALSajbr7.mp3",
  },
  {
    title: "Clearing Fears",
    description: "Learn to focus on what you can control & to quiet your fears",
    belongsTo: "none",
    category: Category.anxiety,
    img: "hand.svg",
    type: Type.single,
    id: 51,
    duration: 547,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/rtmi4k/1540_Clearing_Fears_Held_in_the_Body_Scan_9_min_VOCALS8kge3.mp3",
  },
  {
    title: "Handle Insecurity",
    description:
      "Learn to quiet your insecurities and replace it with inspiration.",
    belongsTo: "none",
    category: Category.anxiety,
    img: "wave.svg",
    type: Type.single,
    id: 52,
    duration: 1185,
    reward: 20,
    url: "https://mcdn.podbean.com/mf/web/xm4jyj/390_Handle_Insecurity_VOCALS92hmv.mp3",
  },
  {
    title: "Seize the Day",
    description: "Prepare yourself to crush the day ahead.",
    belongsTo: "none",
    category: Category.anxiety,
    img: "sun.svg",
    type: Type.single,
    id: 53,
    duration: 626,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/rucidp/1398_Seize_the_Day_Morning_Meditation_VOCALSb63wx.mp3",
  },
  {
    title: "Bedtime Meditation",
    description: "Relax & fall asleep to this peaceful meditation",
    belongsTo: "none",
    category: Category.sleep,
    img: "sheep.svg",
    type: Type.single,
    id: 54,
    duration: 590,
    reward: 10,
    url: "https://mcdn.podbean.com/mf/web/rucidp/1398_Seize_the_Day_Morning_Meditation_VOCALSb63wx.mp3",
  },
  {
    title: "Intro to Meditation",
    description:
      "Learn how to meditate and why making it a habit can drastically improve happiness, focus and so much more",
    belongsTo: "none",
    category: Category.beginners,
    img: "juiceBoxes.svg",
    type: Type.course,
    id: 6,
    duration: 0,
    reward: 0,
    url: "1d",
  },
  {
    title: "7 Days to Happiness",
    description:
      "A 7 day series, where we use meditation to become focused, happier and motivated.",
    belongsTo: "none",
    category: Category.growth,
    img: "kiwi.svg",
    type: Type.course,
    id: 14,
    duration: 0,
    reward: 0,
    url: "",
  },
  {
    title: "Timed Meditation",
    description:
      "Timed unguided (no talking) meditation, with the option to turn on background noises such as rain. A bell will signal the end of your session.",
    belongsTo: "none",
    category: Category.unguided,
    img: "chatBubble.svg",
    type: Type.course,
    id: 2,
    duration: 0,
    reward: 0,
    url: "",
  },
  {
    title: "Meditation for Focus",
    description:
      "A simple 5 minute guided meditation to help you calm your mind, and enter a relaxed focused state.",
    belongsTo: "none",
    category: Category.focus,
    img: "magnifyingGlass.svg",
    type: Type.single,
    id: 25,
    duration: 315,
    reward: 5,
    url: "https://mcdn.podbean.com/mf/web/7d2g5m/Meditation_for_Focus8fetr.mp3",
  },
];
